export const TOTAL_H = 3150;
export const SEM_H = [360, 360, 360, 360, 360, 360, 630, 180];
export const SEM_LABELS = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII'];

/** @typedef {{ id: string, sem: number, nome: string, tipo: string, h: number, pre: string[] }} Disciplina */

/** @type {Disciplina[]} */
export const DISCS = [
  /* 1 */ { id: 'd01', sem: 1, nome: 'Algoritmos e Programação',                    tipo: 'CCO', h: 60, pre: [] },
          { id: 'd02', sem: 1, nome: 'Leitura e Produção de Gêneros Acadêmicos',     tipo: 'COM', h: 60, pre: [] },
          { id: 'd03', sem: 1, nome: 'Fundamentos de Sistemas de Informação',        tipo: 'CCO', h: 60, pre: [] },
          { id: 'd04', sem: 1, nome: 'Matemática Discreta I',                        tipo: 'MAT', h: 60, pre: [] },
          { id: 'd05', sem: 1, nome: 'Introdução à Ciência da Computação',           tipo: 'CCO', h: 60, pre: [] },
          { id: 'd06', sem: 1, nome: 'Inglês Aplicado à Computação',                 tipo: 'COM', h: 60, pre: [] },
  /* 2 */ { id: 'd07', sem: 2, nome: 'Linguagem de Programação I',                   tipo: 'CCO', h: 60, pre: ['d01'] },
          { id: 'd08', sem: 2, nome: 'Organização e Arquitetura de Computadores',    tipo: 'CCO', h: 60, pre: [] },
          { id: 'd09', sem: 2, nome: 'Computador, Ética e Sociedade',                tipo: 'COM', h: 60, pre: [] },
          { id: 'd10', sem: 2, nome: 'Matemática Discreta II',                       tipo: 'MAT', h: 60, pre: ['d04'] },
          { id: 'd11', sem: 2, nome: 'Cálculo Diferencial Aplicado à Computação',   tipo: 'MAT', h: 60, pre: ['d04'] },
          { id: 'd12', sem: 2, nome: 'Administração',                                tipo: 'COM', h: 60, pre: [] },
  /* 3 */ { id: 'd13', sem: 3, nome: 'Linguagem de Programação II',                  tipo: 'CCO', h: 60, pre: ['d07'] },
          { id: 'd14', sem: 3, nome: 'Estruturas de Dados',                          tipo: 'CCO', h: 60, pre: ['d07'] },
          { id: 'd15', sem: 3, nome: 'Sistemas Operacionais',                        tipo: 'TEC', h: 60, pre: ['d08'] },
          { id: 'd16', sem: 3, nome: 'Probabilidade e Estatística',                  tipo: 'MAT', h: 60, pre: ['d10'] },
          { id: 'd17', sem: 3, nome: 'Direito e Legislação em Informática',          tipo: 'HUM', h: 60, pre: [] },
          { id: 'd18', sem: 3, nome: 'Organizações, Sistemas e Métodos',             tipo: 'COM', h: 60, pre: [] },
  /* 4 */ { id: 'd19', sem: 4, nome: 'Metodologia da Pesquisa Científica',           tipo: 'COM', h: 60, pre: [] },
          { id: 'd20', sem: 4, nome: 'Análise e Modelagem de Sistemas',              tipo: 'TEC', h: 60, pre: ['d14'] },
          { id: 'd21', sem: 4, nome: 'Banco de Dados I',                             tipo: 'TEC', h: 60, pre: ['d14'] },
          { id: 'd22', sem: 4, nome: 'Redes de Computadores',                        tipo: 'TEC', h: 60, pre: ['d15'] },
          { id: 'd23', sem: 4, nome: 'Paradigmas de Linguagens de Programação',      tipo: 'CCO', h: 60, pre: ['d13'] },
          { id: 'd24', sem: 4, nome: 'Empreendedorismo',                             tipo: 'COM', h: 60, pre: [] },
  /* 5 */ { id: 'd25', sem: 5, nome: 'Programação para a Web',                       tipo: 'TEC', h: 60, pre: ['d13', 'd21'] },
          { id: 'd26', sem: 5, nome: 'Processo de Desenvolvimento de Software',      tipo: 'COM', h: 60, pre: ['d20'] },
          { id: 'd27', sem: 5, nome: 'Banco de Dados II',                            tipo: 'TEC', h: 60, pre: ['d21'] },
          { id: 'd28', sem: 5, nome: 'Projeto e Administração de Redes',             tipo: 'TEC', h: 60, pre: ['d22'] },
          { id: 'd29', sem: 5, nome: 'Complexidade de Algoritmos',                   tipo: 'CCO', h: 60, pre: ['d11', 'd14'] },
          { id: 'd30', sem: 5, nome: 'Economia',                                     tipo: 'COM', h: 60, pre: [] },
  /* 6 */ { id: 'd31', sem: 6, nome: 'Inteligência Artificial',                      tipo: 'CCO', h: 60, pre: ['d13', 'd10'] },
          { id: 'd32', sem: 6, nome: 'Contabilidade Geral e de Custos',              tipo: 'COM', h: 60, pre: [] },
          { id: 'd33', sem: 6, nome: 'Engenharia de Software',                       tipo: 'TEC', h: 60, pre: ['d26'] },
          { id: 'd34', sem: 6, nome: 'Segurança e Auditoria de Sistemas',            tipo: 'TEC', h: 60, pre: ['d22'] },
          { id: 'd35', sem: 6, nome: 'Sistemas Distribuídos',                        tipo: 'TEC', h: 60, pre: ['d22'] },
          { id: 'd36', sem: 6, nome: 'Optativa A',                                   tipo: 'OPT', h: 60, pre: [] },
  /* 7 */ { id: 'd37', sem: 7, nome: 'Qualidade de Software',                        tipo: 'TEC', h: 60, pre: ['d33'] },
          { id: 'd38', sem: 7, nome: 'Trabalho de Conclusão de Curso I',             tipo: 'SUP', h: 60, pre: [] },
          { id: 'd39', sem: 7, nome: 'Interface Homem-Máquina',                      tipo: 'TEC', h: 60, pre: ['d33'] },
          { id: 'd40', sem: 7, nome: 'Estágio Supervisionado',                       tipo: 'SUP', h: 60, pre: [] },
          { id: 'd41', sem: 7, nome: 'Gestão de Projetos',                           tipo: 'TEC', h: 60, pre: ['d26', 'd33'] },
          { id: 'd42', sem: 7, nome: 'Optativa B',                                   tipo: 'OPT', h: 60, pre: [] },
          { id: 'd43', sem: 7, nome: 'Gestão e Governança de TI',                   tipo: 'TEC', h: 60, pre: [] },
  /* 8 */ { id: 'd44', sem: 8, nome: 'Meio Ambiente',                                tipo: 'HUM', h: 60, pre: [] },
          { id: 'd45', sem: 8, nome: 'Trabalho de Conclusão de Curso II',            tipo: 'SUP', h: 60, pre: [ 'd38' ] },
          { id: 'd46', sem: 8, nome: 'Sistemas de Apoio a Decisão',                  tipo: 'TEC', h: 60, pre: ['d01'] },
          { id: 'd47', sem: 8, nome: 'Optativa C',                                   tipo: 'OPT', h: 60, pre: [] },
          { id: 'd48', sem: 8, nome: 'Optativa D',                                   tipo: 'OPT', h: 60, pre: [] },
];
